name: Infrastructure.MySql

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: \d*\.\d*\.(\d*)\</Version
        replace: "1.0.garbonzobeans</Version"
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "garbonzobeans"
        replace: $GITHUB_RUN_NUMBER
    - name: Pack
      run: dotnet pack --configuration Release Melberg.Infrastructure.MySql/Melberg.Infrastructure.MySql.csproj 
    - name: Push
      run: dotnet nuget push Melberg.Infrastructure.MySql/bin/Release/Melberg.Infrastructure.MySql* --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
