name: Pack And Push

on:
  push:
    branches: [ master ]
  workflow_dispatch:
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup env
      uses: jwulf/add-env-vars-action@master
      with:
        map: '{"vers": "1.0.${{ github.run_number }}</Version"}'
    - name: show
      run: echo $vers
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: \d*\.\d*\.(\d*)\</Version
        replace: ${{env.vers}}
    - name: Pack Infrastructure.Couchbase
      run: dotnet pack --configuration Release Melberg.Infrastructure.Couchbase/Melberg.Infrastructure.Couchbase.csproj 
    - name: Push Infrastructure.Couchbase
      run: dotnet nuget push Melberg.Infrastructure.Couchbase/bin/Release/Melberg.Infrastructure.Couchbase* --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
    - name: Pack Infrastructure.MySql
      run: dotnet pack --configuration Release Melberg.Infrastructure.MySql/Melberg.Infrastructure.MySql.csproj 
    - name: Push Infrastructure.MySql
      run: dotnet nuget push Melberg.Infrastructure.MySql/bin/Release/Melberg.Infrastructure.MySql* --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
